### ISSUE TITLE
NPM registry error

### ISSUE THREAD

**Issue by BasharAG** [26medias/AIStock#1]
Tradestudio no longer exists in the NPM registry

**Comment by 26medias** [comment]
Hi,

This project is deprecated. Some of the dependencies do not exist anymore.

I have moved on to other projects, but they are not open-source at this time.

If you want to build your own, you can quick-start your project using:

- Get the stock data using https://www.npmjs.com/package/node-activetick (requires a $50/month subscription at activetick.com)
- Process the data using https://www.npmjs.com/package/timeseries-analysis
